### ISSUE TITLE
not an issue. But need a permission

### ISSUE THREAD

**Issue by aferust** [burakkunkcu/image-stitching#1]
Hello, thank you for the great work! I have converted your code to dlang to be used in [DCV](https://github.com/libmir/dcv)(open source computer vision library for dlang with licence Boost 1.0). I kindly ask for a permission to use the dlang translation of your code with DCV.  Your name and a link to this repo will be preserved in the source file. I am one of the maintainers of DCV.

Thanks in advance!

Merhaba Burak Bey, 
Bu harika çalışmanız için teşekkür ederim! Kodunuzu [DCV](https://github.com/libmir/dcv). Boost 1.0 lisansı ile dlang için açık kaynak bilgisayarlı görme kitaplığı) içinde kullanılmak üzere dlang dilinde yeniden yazdım. Kodunuzun dlang çevirisini DCV ile kullanmak için izin rica ediyorum. Adınız ve bu depoya olan bağlantı kaynak dosyada korunacaktır. Ben DCV'nin maintainerlarından biriyim.

Şimdiden teşekkürlerimi sunarım.

**Comment by kunkcu** [comment]
Merhaba Ferhat Bey,

Öncelikle geç cevap verebildiğim için kusura bakmayın. Tabii, kodu bahsettiğiniz şekilde kullanmanızda benim için herhangi bir sakınca yok. Aksine memnun olurum. 

Ancak belirtmek isterim ki bu kod temel konseptleri öğrenirken yazdığım ardından başkalarına da faydalı olacağını düşünerek performanstan çok okunabilirliği göz önünde bulundurarak düzenlediğim bir çalışmadır. Bununla birlikte _"image stitching"_ probleminin özüne odaklanmış olup ileri seviye uygulamalarda gerekli olabilecek bazı ek konuları (örneğin _camera distortion_, _color consistency_ gibi) adreslememektedir.

**Comment by aferust** [comment]
Teşekkür ederim Burak Bey. Kodu çevirirken benim için de bir öğrenme aşaması oldu. Şu an için eksisklikler olması önemli değil. Temel fonksiyon çalışması yeterli.
